on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created == 'true' }}
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Auto Tag
        uses: graasp/graasp-deploy/.github/actions/auto-tag-after-release@v1
        with:
          releases_created: ${{ steps.release.outputs.releases_created }}
          tag_name: ${{ steps.release.outputs.tag_name }}

      - name: Publish to NPM
        uses: graasp/graasp-deploy/.github/actions/publish-to-npm@v1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.releases_created == 'true' }}
