on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: graasp-chatbox
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"docs","section":"Documentation","hidden":false}]'

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          ref: ${{ steps.release.outputs.tag_name }}

      - name: Tag major and minor versions
        uses: jacobsvante/tag-major-minor-action@v0.1
        if: ${{ steps.release.outputs.release_created }}
        with:
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}

      # -------------------------------------------------------------------------
      # This section is useful only if you plan on publishing your package to NPM
      # Remove it if you do not plan to publish to NPM
      - name: Publish to NPM
        uses: graasp/graasp-deploy/.github/actions/publish-to-npm@v1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
      # -------------------------------------------------------------------------
