name: Run tests
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: Run Component tests 🧪
        uses: cypress-io/github-action@v2
        with:
          # to run component tests we need to use "cypress run-ct"
          command: yarn cypress run-ct
