name: Run tests
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: yarn

      - name: cypress test
        run: yarn cypress:ci
